### ISSUE TITLE
27-31 May 2018, Noordwijkerhout: 11th International Conference on Chemical Structures

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/events#247]
http://www.int-conf-chem-structures.org/

With @egonw [amongst the organizers](http://www.int-conf-chem-structures.org/organizers.html), which may prevent him from attending WikiCite (#201).

Perhaps an opportunity to do something about Wikidata/ WikiCite & chemistry?

**Comment by egonw** [comment]
We submitted a poster about chemistry in Wikidata, which will include Scholia and the link to literature, and as such cover various WikiCite efforts.

**Comment by Daniel-Mietchen** [comment]
Is the submission somewhere public?

**Comment by egonw** [comment]
Not at this moment.
