### ISSUE TITLE
28 December 2017, global: submission deadline for session proposals for RDA 11

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/events#285]
as per
https://www.rd-alliance.org/rda-11th-plenary-call-sessions
and
https://github.com/Daniel-Mietchen/events/issues/204

**Comment by Daniel-Mietchen** [comment]
Maybe put in something about 
- Wikidata
- making ethics data FAIR

**Comment by Daniel-Mietchen** [comment]
Oya will check with Organizing committee about what the best way would be to get the FAIR ethics into the programme.

**Comment by Daniel-Mietchen** [comment]
Potential starting point: http://sagebase.org/governance/participant-centered-consent-toolkit/

**Comment by oyadenizbeyan** [comment]
https://github.com/ga4gh/ADA-M

**Comment by Daniel-Mietchen** [comment]
There was a SWAT4HCLS poster "Implementing ELSI 2.0 for international collaborative research: improving access to clinical and genetics data by connecting ELSI policies, FAIR data software solutions, and ELIXIR-AAI" (ELSI stands for "Ethical, Legal and Social Implications") but the author could not make it to the event, the poster did not contain contact details, and no further information is available from the conference website. Her contact details are at http://rd-connect.eu/person/sabina-gainotti/ .
