### ISSUE TITLE
15 April 2018, global: abstract submission deadline for 10th International Conference on Ecological Informatics

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/events#339]
as per
#338
and
http://icei2018.uni-jena.de/calls/

idea: Wikidata on ecological informatics

note there's also a call for demos, deadline July 15.

**Comment by Daniel-Mietchen** [comment]
The deadline has been extended to April 15. Will try to submit in March though.

**Comment by Daniel-Mietchen** [comment]
From http://icei2018.uni-jena.de/program/#themes :
- S1.6 _ Semantics for biodiversity and ecosystem research. (Session Chairs: Alsayed Algergawy, Clement Jonquet, Naouel Karam, Friederike Klan, Nikos Minadakis, Alessandro Oggioni and Ilaria Rosati)
  - This would fit with Scholia. Pinging @fnielsen.
- S3.2 _ Citizen science meets informatics: Data science challenges in ecological research with public participation. (Session Chairs: Friederike Klan and Jana Wäldchen) .
  - Here, something along the lines of https://ecsa.citizen-science.net/working-groups/citizen-science-and-open-science/wikidata-collaborative-public-domain-knowledge-graph but digging a bit deeper would fit
- S3.1 _ Eco-metabolomics meets eco-informatics: Identifying ecologically relevant compounds in metabolomics datasets. (Session Chairs: Nicole van Dam, Christoph Steinbeck and Steffen Neumann)
  - I won't do this one alone but someone like @egonw might be interested in doing this together.
- S3.6 _ Efficient data and workflow management for reaching Sustainable Development Goals (SDGs) targets associated to biodiversity and ecosystems. (Session Chairs: Jan Bumberger, Jitendra Gaikwad and Aidin Niamir)
  - This would fit with efforts to model SDGs in Wikidata

**Comment by fnielsen** [comment]
https://tools.wmflabs.org/scholia/event/Q50706744

**Comment by egonw** [comment]
https://tools.wmflabs.org/scholia/event/Q47501229

**Comment by egonw** [comment]
S3.1 is interesting... what compounds are detected as polution in what ecological areas...

(But seriously, I don't time for additional meetings before summer...)

**Comment by Daniel-Mietchen** [comment]
@egonw I'll be attending this one, as it is in town, so you wouldn't have to come.

**Comment by Daniel-Mietchen** [comment]
Re S1.6: I am reviewing what we currently have for taxa and thinking how to combine this with some of the other well-curated corners of Wikidata/ Scholia, e.g. chemicals (e.g. [found in taxon](https://www.wikidata.org/wiki/Property:P703)), geolocation (think invasive species), diseases (think pathogens) and such.

Re S3.2: My ECSA submission on that was [somewhat accepted](https://www.wikidata.org/w/index.php?title=User%3ADaniel_Mietchen%2FECSA_2018&type=revision&diff=659189520&oldid=658064977) &mdash; could perhaps serve as a basis for submitting something ecologically flavoured here.

Re S3.1: I will not pursue this further for now, but include it in the chemical side of considerations for S1.6 (see above).

Re S3.6: I have https://github.com/Daniel-Mietchen/ideas/issues/640 for that and am planning to include biodiversity-related topics there soon, though not sure I can make it in time for this conference deadline.

**Comment by Daniel-Mietchen** [comment]
S1.6 now has a dedicated ticket: https://github.com/fnielsen/scholia/issues/290 .

**Comment by Daniel-Mietchen** [comment]
"[Abstracts should not be more than one A4 size page (max. 400 Words)](http://icei2018.uni-jena.de/calls/)"

**Comment by egonw** [comment]
the "found in taxon" for metabolite is very badly populated; there is very little quality CCZero data available :(

**Comment by Daniel-Mietchen** [comment]
I have started drafting some potential submissions: https://github.com/Daniel-Mietchen/events/blob/master/ICEI2018.md .

@fnielsen @egonw please add yourselves to https://github.com/Daniel-Mietchen/events/blob/master/ICEI2018-research-ecosystem.md (which is about S1.6) and edit the file as you see fit, keeping in mind the 400 word-limit that includes submission metadata.

I plan to submit on Saturday, i.e. about a day before the deadline.

**Comment by Daniel-Mietchen** [comment]
@fnielsen @egonw Semi-final drafts for three submission candidates are up at https://github.com/Daniel-Mietchen/events/blob/master/ICEI2018.md . Please chime in today if you want to be part of any of them.

**Comment by fnielsen** [comment]
Thanks for the invitation. You can write me on if you think I have contributed enough. I suppose the most relevant in terms of my possible contribution is _Visualizing the research ecosystem of ecosystem research via Wikidata_. You have possible got an alert from GitHub concerning a recent extension of Scholia's taxon tree. I wonder you want other changes to Scholia in relation to the deadline. 

"about 50 million" should (I suppose) be "about 46 millions" according to the frontpage

**Comment by Daniel-Mietchen** [comment]
Thanks. I was offline during the day, so hadn't seen the new taxon query yet. Now that I have had a look, I think that is good progress. I do not expect further changes to Scholia by the deadline of tomorrow, but am quite confident that we will do quite a bit more on taxa until the conference actually takes place in September.
Until then, the stats will have changed quite a bit as well, so I went for only one significant figure for all of them. I have put in @fnielsen and @egonw as co-authors on the Scholia submission and plan to submit later tonight/ early tomorrow.

**Comment by Daniel-Mietchen** [comment]
I have submitted all three proposals. Not sure I'll have a chance to look at them again before the deadline.

**Comment by egonw** [comment]
I'm sorry I did not have time to look at it. I'll look at it now.

**Comment by egonw** [comment]
See https://github.com/Daniel-Mietchen/events/pull/390

**Comment by Daniel-Mietchen** [comment]
Thanks. I merged your suggestions, did some further brushing and then resubmitted.

**Comment by egonw** [comment]
Thanks for putting it together. I will pass it along to Antony Williams and Emma Schmymanski.

**Comment by Daniel-Mietchen** [comment]
Just in:

> we are happy to inform you that your abstract
>
> ID: 143
> Title: Visualizing the research ecosystem of ecosystem research via Wikidata
> 
> has been accepted for presentation at the special session "Semantics for Biodiversity and Ecosystem Research" co-located with the International Conference on Ecological Informatics (ECEI) in Jena (24-28 September 2018). Congratulations! Further instructions for the submission of the camera-ready version of your abstract will follow soon.

**Comment by fnielsen** [comment]
"These items are annotated and linked via almost 5000 'properties' like that describe relationships between items or between items and external entities or that express specific value." 

"like" superfluous?

"express specific value." -> "express a specific valu"?
