### ISSUE TITLE
6-12 October 2019, global: Second Annual Global World Commons Week

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/events#581]
as per
https://www.worldcommonsweek.org/ (currently still displaying last year's info).

Submission form to indicate an interest in organizing a local event:
https://docs.google.com/forms/d/e/1FAIpQLScdWKDtW2IIFxi1RiMnXIUeUAPJ8g4OIKyDr4VJEsGIboUdEw/viewform

Also pinging @bluerasberry .

**Comment by bluerasberry** [comment]
I expect that WikiConference North America will be that week.

https://meta.wikimedia.org/wiki/WikiConference_North_America

I filled out their form to inform them of our conference in their area. If they respond to that then I will send them invitations to join and present.
