### ISSUE TITLE
15 March 2020, global: Abstract submission deadline for Workshop "Data Science in Climate and Climate Impact Research"

### ISSUE THREAD

**Issue by Daniel-Mietchen** [Daniel-Mietchen/events#644]
as per
https://github.com/Daniel-Mietchen/events/issues/643
and
https://wcr.ethz.ch/news-and-events/events/workshop--data-science-in-climate-and-climate-impact-research-.html

**Comment by Daniel-Mietchen** [comment]
Pinging @criscod for a joint submission around Wikidata.

**Comment by Daniel-Mietchen** [comment]
Here are some more details from the workshop description:

> Details
> 
> In recent decades, the production and storage of data about practically every aspect of human life has increased. This concerns scientific research in general, including environmental sciences. Increasing volumes of data help environmental scientists to observe more phenomena at a finer spatial and temporal scale and to model phenomena with machine learning. These new possibilities raise a host of interesting methodological questions. In a policy-​relevant field such as climate science and climate impact research, transparency of and confidence in results is key. However, it is unclear how these features can be achieved when employing data science. Furthermore, data science projects often require extensive interdisciplinary collaboration in order to combine expertise in handling and analyzing data and domain expertise. This helps to obtain meaningful insights from the data. However, this interdisciplinarity can be associated with new challenges.
> 
> There are numerous examples of interesting data-​science projects in climate and climate impact research, which have addressed a variety of purposes. For example, innovative methods that combine physical modeling and machine learning might be employed to analyze environmental data while ensuring interpretability and physical plausibility of the models. New forms of data might help to measure environmental conditions and monitor policy implementation or to monitor disaster response and climate change adaptation. But how should these attempts be evaluated? What role does interdisciplinary collaboration play in these efforts? What purposes are data sciences tools most fruitful for and under what conditions?
> 
> At this interdisciplinary conference, we aim to bring together researchers from all climate-​related subdisciplines (including environmental social science and climate impact research), philosophers, and environmental data scientists to discuss questions like these. While case studies are welcome, the emphasis on the talks should be on conceptual issues.
> 
> Topics
> 
> Questions that can be discussed include (but are not limited to) the following:
> 
> - What purposes are new kinds of data most fruitful for?
> - Which research questions can be addressed using machine learning? Is machine learning equally attractive for understanding as it is for prediction?
> - How should machine learning models and new forms of data be evaluated in order to assess their reliability? Does this depend on the purpose of a research project?
> - What is the role of scientific theories and domain-​specific background knowledge when constructing and applying data-​science tools?
> - How does interpretability/transparency affect the evaluation of the models and data? What is the role of interpretable algorithms and well-​documented data? How does this depend on the specific purpose?
> - How should uncertainties arising from new sources or forms of data or automated data analysis tools be understood and characterized? How can they be handled in decision-​making?
> - What is the relationship between transparency of models and data on the one hand and uncertainty on the other hand?
> - How should interdisciplinary teams for environmental data-​science projects be organized? What kind of collaboration is needed?

A starting point on the Wikidata end would be 
https://www.wikidata.org/wiki/Wikidata:WikiProject_Climate_Change .

**Comment by Daniel-Mietchen** [comment]
Nice update from the organizers (emphasis added):
>  The deadline for abstract submission has been extended **until April 6**. We will notify all applicants until April 20, 2020.

> **It is possible to give talks remotely**, so you can also submit an abstract if you cannot travel to Zurich.

So I think I'll give it a go.

**Comment by criscod** [comment]
Brainstorming what to present: 

- **Showcasing the exploration of Wikidata's content relevant for Climate Research**: following Daniel's suggestion and his past presentation, the submission could focus on classes & items related to the domain of Climate Research, tools to explore Wikidata, publication metadata and Scholia. For the presentation, we could also try to mine the query log to find examples of queries that were executed to obtain some data around any research discipline. 

- **Explaining Wikidata's special features in terms of knowledge management**: structured data, ranks, references, community editing towards an increase of schema quality/data accuracy/data completeness, bots, discussions and collaboration to create and monitor data, open source tool development. For the presentation in August, we could think of compiling useful stats that accompany the explanation of these features.

**Comment by Daniel-Mietchen** [comment]
Thanks - have added that to a [Gdoc](https://docs.google.com/document/d/17Tkb3udX0EbTWhN1DrTCPvWomScPlJhwAlJcGal-6ZQ/edit) we can use for drafting.

**Comment by Daniel-Mietchen** [comment]
Our abstracts sit at https://github.com/Daniel-Mietchen/events/blob/master/data-science-in-climate-and-climate-impact-research.md .
